services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sraz'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '127.0.0.1:5436:5432'
